### ISSUE TITLE
csv_convert fails if CSV doesn't include a "page" column

### ISSUE THREAD

**Issue by weaversam8** [fross123/csv_to_qlab#74]
**Describe the bug**
If your CSV doesn't include a "page" column, this app surfaces an Internal Server Error. The stacktrace:

```
Traceback (most recent call last):
  File "/.../csv_to_qlab/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/.../csv_to_qlab/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/.../csv_to_qlab/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/.../csv_to_qlab/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/.../csv_to_qlab/application.py", line 38, in upload_file
    send_csv(ip, uploaded_file, ql5_passcode)
  File "/.../csv_to_qlab/csv_convert.py", line 80, in send_csv
    if cue["page"] and cue["notes"]:
```

**Comment by weaversam8** [comment]
As an aside, I had to compile and run this myself in python to catch the error - perhaps it would be helpful to show error messages in the UI, even if it's just the raw stacktrace.

**Comment by fross123** [comment]
@weaversam8 Thank you very much for flagging this!

I just tested the app with both the [simple.csv ](https://github.com/fross123/csv_to_qlab/blob/main/static/example_file/simple.csv) and [example.csv](https://github.com/fross123/csv_to_qlab/blob/main/static/example_file/example.csv) csv files that are in the repository and I am not seeing an error. simple.csv does not have page or notes columns, the example.csv has both.

What version are you running? It's not super likely, but I do know this was a bug I had fixed a while back. Most recent should say version 2022.3.

What columns did you have in the file that throwing the error?

You'll have to forgive me on the simplicity of the app, I built it mostly for myself and decided to publish it with a UI in case it helps others too. It is definitely a work in progress. I absolutely agree with you about handling errors, it's just a matter of having time to do so. Tests are a bit higher on my priority list before I try to add more to it, but I will see what I can do. If you would like to take a crack at it, I would be more than happy to review a PR because I think error handling in the UI would be an excellent addition to this app.

**Comment by fross123** [comment]
See [v.2023.2](https://github.com/fross123/csv_to_qlab/releases/tag/v2023.2) for error reporting and other minor fixes.
